name: Build Eidolon
on: workflow_dispatch
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 修复 Node.js 20 报错
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: edayot/eidolon
          ref: main
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: eidolonmc-linux-x86_64
          path: target/release/eidolonmc
